name: Publish Website
on:
    push:
        branches: [ web ]
    # allows us to run the workflow manually
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    # build job
    build:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            # basic node setup
            - name: Use Node.js 20.x
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
            - run: npm ci
            - run: npm run build
            # setup page run
            - name: Setup Pages
              uses: actions/configure-pages@v3
            # upload the artifact
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                # Upload build folder
                path: 'build/'
            # deploy the page!
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2